class RouteNames{
  static const String Home="/";
  static const String Login="/login";
  static const String Signup="/signup";
  static const String EditProfile="/editprofile";
  static const String Settings="/settings";
  static const String Complaint="/complaints";
  // static const String AddReply="/addreply";
  // static const String ShowPost="/showpost";
  static const String ShowImage="/showimage";
  // static const String AddPost="/addpost";
  static const String Chatbot="/chatbot";
  static const String CheatingStudents="/cheatingstudents";
  static const String WriteApplication="/writeapplication";
  static const String MapScreen="/mapscreen";
  static const String Election="/election";
  static const String Voting="/voting";
  static const String CampusBooking="/campusbooking";
  static const String IdProof="/idproof";
  static const String NoElections="/noelections";
  static const String ElectionResults="/electionresults";
  static const String DispensaryAppointment="/dispensaryappointment";
  static const String StudentsComplaints="/studentscomplaints";
  static const String AllBookings="/allbookings";

// static const String ShowProfile="/showprofile";
// static const String ShowPlant="/showplant";
// static const String ShowDisease="/showdisease";
// static const String InformationZone="/informationzone";
// static const String Predict="/predict";
// static const String Healthy="/healthy";
// static const String ShowSoil="/showsoil";
// static const String ShowSeason="/showseason";
// static const String MyCrops="/mycrops";
// static const String ManageInfo="/manageinfo";
// static const String ManagePlant="/manageplant";
// static const String TopFarmers="/topfarmers";
// static const String ShowFarmer="/showfarmer";
}